# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 166dc2c75cc93e8221ea38107111cd8b16aeb332ac2a83f8be37f633a99e6b298ca8b602d132b7a1974e83dfb2a436ca438da829f37f1b732e55305998237a8d

test:
  secret_key_base: 645b02bdc100b771b92e57add1fcacd8dd3a4570fbcf8f1920557f583e5976e6f3ddef5ca43812d09ea451f233b3cb81fd0105a4a2915fd07060a27ce2353d2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
